### ISSUE TITLE
Campaign #1 - 06/21/2015

### ISSUE THREAD

**Issue by jeanlucaslima** [StartupStudyGroup/ssg-weekly#1]
_Weekly to be sent date 06/21/2015_

Help SSG Weekly posting your link or suggestion here in the comments for this issue. 
Along the week we will debate and collect the best material and links to be inserted in next issue. 
### Template for one suggestion (not mandatory, you can do your way):

**Title:** A good title
**Link:** URL
**Description:** A short description about the link
**Category:** Suggest a category for the link
**Obs:** Any relevant information. 
### Example:

**Title:** New Node.js version available
**Link:** http://blog.nodejs.org/2015/02/06/node-v0-12-0-stable/
**Description:** New stable release to Node.js (0.12).
**Category:** News.
**Obs:** The new version support ES6 template strings.

**Comment by jeanlucaslima** [comment]
**Title:** Ryan Hoover in 40 seconds
**Link:** https://medium.com/@JDcarlu/ryan-hoover-in-40-seconds-39d054e4472
**Description:** New blog post on Ryan Hoover video on YouPlus.biz
**Category:** News.

**Comment by webhat** [comment]
Is this send before or after Slack's Startup Study Group's Weekly Summary, if it's after we should include some stats.

**Comment by jeanlucaslima** [comment]
@webhat good idea to send right after.

**Comment by webhat** [comment]
**Title:** Don’t Meet With an Investor Unless They Match These Three Criteria
**Link:** https://medium.com/startup-study-group/don-t-meet-with-an-investor-unless-they-match-these-three-criteria-727f5090f81c
**Description:** 3 things target when looking for investors.
**Category:** Investment
**Obs:**

**Comment by webhat** [comment]
**Title:** The Difference Between Raising a Seed and Series A Round
**Link:** https://medium.com/@StephenForte/the-difference-between-raising-a-seed-and-series-a-round-90a957e7ee87
**Description:** 
**Category:** Raising a Round
**Obs:**

**Comment by webhat** [comment]
**Title:** 10 Titles to Watch for Entrepreneurial Inspiration
**Link:** https://medium.com/@srenriber/10-titles-to-watch-for-entrepreneurial-inspiration-e9376588ec09
**Description:** 
**Category:** Entrepreneur
**Obs:**

**Comment by webhat** [comment]
**Title:** 4-Point Story Structure for Fundraising
**Link:** https://medium.com/startup-study-group/4-point-story-structure-for-fundraising-a78e330e2afe
**Description:** 
**Category:** Raising a Round
**Obs:**
